export default {
  colors: {
    transparent: 'transparent',
    apple: '#33CC33',
    navy_blue: '#000099',
    screamin_green: '#55EE55',
    pastel_green: '#90EE90',
    link_water: '#D9D9F4',
    carnation: '#F24F4F',
    white_lilac: '#f0f0fa',
    azure_radiance: '#0993F8',
    white: '#FFFFFF',
    alabaster: '#FAFAFA',
    iron: '#E9E9EA',
    silver_sand: '#C7C9CB',
    rolling_stone: '#797D81',
    outer_space: '#363C42',
    bunker: '#141C23',
    black: '#000000',
    back: '#e0e0e0',
    gray: '#8E8E8E',
    panache: '#F2F9F5',
    christi: '#2DC913',
    supernova: '#FDC602',
    red_orange: '#FF2525',
    feta: '#EAFAE7',
    early_dawn: '#FFF9E6',
    chablis: '#FFF1F1',
    anakiwa: '#A0C4FF',
    melrose: '#BDB2FF',
    pink_lace: '#FFC6FF',
    light_anakiwa: '#9BF6FF',
    navajo_white: '#FFD6A5',
    cornflower_ilac: '#FFADAD',
    san_juan: '#334872',
    bittersweet: '#FF6060',
  },
  fonts: {
    Poppins: {
      Bold: 'Poppins-Bold',
    },
    OpenSans: {
      Semi_Bold: 'OpenSans-SemiBold',
      Regular: 'OpenSans-Regular',
    },
    fontSize: {
      xxsmall: 6,
      xsmall: 8,
      small: 12,
      smallRegular: 14,
      regular: 16,
      medium: 18,
      large: 20,
      extraLarge: 24,
    },
  },
};
